private policy
nwplus/www pull request #179
Opened 2023-11-16 08:13 UTC by samanthatuhseng

![](https://media.giphy.com/media/xuXzcHMkuwvf2/giphy.gif)

## Description

This PR adds a new `privacy.js` page to our application, which contains our updated privacy policy. It provides users with detailed information about the data we collect, how we use it, and their rights regarding their data.

Changes made:
- Added a new `privacy.js` page.
- Included sections for key points, preface, terminology, data collection, data sharing, and user rights.
- put each section with relevant content regarding our privacy policy.

## Other considerations

possible future changes: consistency and design

2023-11-16 22:04 UTC, michelleykim requested changes
Hey, thanks for getting this done so quickly! It seems like the header overlaps with the content on privacy page, wondering if it's just me or do you also see this?
![image](https://github.com/nwplus/www/assets/33190160/295dfbe2-969a-4a87-a568-a9bf34817b06)

2023-11-17 02:14 UTC, meleongg commented
I also see the weird overlap -> I think the nwHacks apps closed banner needs to be there

2023-11-17 17:23 UTC, michelleykim approved these changes
lgtm, i think we're good to merge once pres give thumbs up

2023-11-19 07:42 UTC, michelleykim approved these changes

2023-11-19 07:42 UTC, merged