Carousel implementation
nwplus/www pull request #19
Opened 2021-07-29 08:52 UTC by dchen150

![screenrecording](https://user-images.githubusercontent.com/45786074/127462328-c175da94-5601-444d-834f-048a3793dbd3.gif)

## Description
Carousel component. Takes a list of images as the input and the width/height of the carousel. Can scroll through images using arrows. Has diamonds to represent which image is currently shown.

## Other considerations
colors aren't right right now

2021-07-29 20:45 UTC, ianmah requested changes
⚠⚠⚠⚠ayo why we have package-lock and yarn lock ⚠⚠⚠⚠

2021-07-29 20:50 UTC, ianmah commented
Let's use this so we support any size of image (and dont stretch it out) 
https://www.w3schools.com/css/css3_object-fit.asp

2021-07-29 20:51 UTC, anneguo3 commented
Can this also auto-scroll without needing to click through the photos? 👀

2021-07-29 21:44 UTC, dchen150 commented
> Can this also auto-scroll without needing to click through the photos? 👀

auto-scrolls every 5 seconds of not being manually scrolled now. Also added object-fit: cover for the image css
![screenrecording](https://user-images.githubusercontent.com/45786074/127569730-96944309-ddd3-48e4-8d16-b8d9adacba42.gif)

2021-07-29 23:31 UTC, kevin-zou commented on components/Carousel.js
> +}
Nit: newline at end of file (we should probably get a linter set up soon)

2021-07-29 23:37 UTC, kevin-zou reviewed
Couple of comments, but looking good! 🚀

2021-07-29 23:37 UTC, kevin-zou commented on components/Carousel.js
> +}
Nit: newline at end of file (we should probably get a linter set up soon)

2021-07-29 23:37 UTC, kevin-zou commented on components/Carousel.js
> +                        </FlexBox>
Can we center this under the image, as per the design?
![image](https://user-images.githubusercontent.com/5078356/127578634-60b5fdaa-a93e-4937-9e14-d83be7f09de1.png)

2021-07-30 04:48 UTC, dchen150 commented
![image](https://user-images.githubusercontent.com/45786074/127601843-47edcab4-cad0-4a4f-b2f5-545415dd4a2b.png)
 diamonds centered and new line added

2021-08-02 19:06 UTC, kevin-zou approved these changes
🔥

2021-08-03 07:32 UTC, merged

2021-08-03 07:53 UTC, kozr commented on components/Carousel.js
> +                )
Probably didn't need the ternary and could've just used `&&`